# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -IWasteland/src -IWasteland/vendor/spdlog/include -IWasteland/vendor/entt/single_include -IWasteland/vendor/glm -IWasteland/vendor/pybind11/include -IC:/Users/rtoue/AppData/Local/Python/pythoncore-3.14-64/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug-windows-x86_64/DemonCore-Editor
TARGET = $(TARGETDIR)/Wasteland.pyd
OBJDIR = obj/Debug
DEFINES += -DWL_PLATFORM_WINDOWS -DWL_BUILD_DLL -DGLFW_INCLUDE_NONE -DWL_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g /utf-8
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++17 /utf-8
LIBS += bin/Debug-windows-x86_64/Wasteland/Wasteland.lib -lpython314 -lopengl32.lib
LDDEPS += bin/Debug-windows-x86_64/Wasteland/Wasteland.lib
ALL_LDFLAGS += $(LDFLAGS) -LC:/Users/rtoue/AppData/Local/Python/pythoncore-3.14-64/libs -L/usr/lib64 -m64 -shared -Wl,--out-implib="bin/Debug-windows-x86_64/DemonCore-Editor/Wasteland.lib"

else ifeq ($(config),release)
TARGETDIR = bin/Release-windows-x86_64/DemonCore-Editor
TARGET = $(TARGETDIR)/Wasteland.pyd
OBJDIR = obj/Release
DEFINES += -DWL_PLATFORM_WINDOWS -DWL_BUILD_DLL -DGLFW_INCLUDE_NONE -DWL_RELEASE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 /utf-8
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++17 /utf-8
LIBS += bin/Release-windows-x86_64/Wasteland/Wasteland.lib -lpython314 -lopengl32.lib
LDDEPS += bin/Release-windows-x86_64/Wasteland/Wasteland.lib
ALL_LDFLAGS += $(LDFLAGS) -LC:/Users/rtoue/AppData/Local/Python/pythoncore-3.14-64/libs -L/usr/lib64 -m64 -shared -Wl,--out-implib="bin/Release-windows-x86_64/DemonCore-Editor/Wasteland.lib" -s

else ifeq ($(config),dist)
TARGETDIR = bin/Dist-windows-x86_64/DemonCore-Editor
TARGET = $(TARGETDIR)/Wasteland.pyd
OBJDIR = obj/Dist
DEFINES += -DWL_PLATFORM_WINDOWS -DWL_BUILD_DLL -DGLFW_INCLUDE_NONE -DWL_DIST
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 /utf-8
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++17 /utf-8
LIBS += bin/Dist-windows-x86_64/Wasteland/Wasteland.lib -lpython314 -lopengl32.lib
LDDEPS += bin/Dist-windows-x86_64/Wasteland/Wasteland.lib
ALL_LDFLAGS += $(LDFLAGS) -LC:/Users/rtoue/AppData/Local/Python/pythoncore-3.14-64/libs -L/usr/lib64 -m64 -shared -Wl,--out-implib="bin/Dist-windows-x86_64/DemonCore-Editor/Wasteland.lib" -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Bindings.o
OBJECTS += $(OBJDIR)/Bindings.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking WastelandPython
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning WastelandPython
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Bindings.o: Wasteland/src/Wasteland/Scripting/Bindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif